version: '3'
services:
  app:
    build: ./puppeteer
    tty: true
    stdin_open: true
    volumes:
      - ./app:/app
      - ./screenshots:/screenshots

  gazosan:
    image: lifullsetg/gazo-san
    tty: true
    stdin_open: true
    volumes:
      - ./screenshots:/screenshots
      - ./output:/output